-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE alert_status
(
    city_id integer NOT NULL REFERENCES city(id),
    start_date_forecasted date NOT NULL,
    end_date_forecasted date NOT NULL,
    cities_gained_csl text NOT NULL,
    cities_lost_csl text NOT NULL,
    did_change boolean NOT NULL,
    max_drive_minutes integer NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX alert_status_city_id_start_date_forecasted_end_date_forecasted_ ON alert_status(city_id
int4_ops,start_date_forecasted date_ops,end_date_forecasted date_ops,max_drive_minutes int4_ops);
CREATE INDEX alert_status_start_date_forecasted_end_date_forecasted_did_chan ON alert_status(start_date_forecasted
date_ops,end_date_forecasted date_ops,did_change bool_ops);
