-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE MATERIALIZED VIEW city_travel_time_all AS  SELECT city_travel_time.citya_id AS city_from_id,
    city_travel_time.cityb_id AS city_to_id,
    city_travel_time.gmap_drive_time_minutes
   FROM city_travel_time
UNION
 SELECT city_travel_time.cityb_id AS city_from_id,
    city_travel_time.citya_id AS city_to_id,
    city_travel_time.gmap_drive_time_minutes
   FROM city_travel_time;

-- Indices -------------------------------------------------------

CREATE INDEX city_travel_time_all_city_from_id_city_to_id_idx ON city_travel_time_all(city_from_id int4_ops,city_to_id int4_ops);
