-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE city_travel_time (
    citya_id integer NOT NULL REFERENCES city(id),
    cityb_id integer NOT NULL REFERENCES city(id),
    gmap_drive_time_minutes integer
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX city_travel_time_city_lookup ON city_travel_time(citya_id int4_ops,cityb_id int4_ops);
CREATE INDEX city_travel_time_citya_drivetime ON city_travel_time(citya_id int4_ops,gmap_drive_time_minutes int4_ops);
CREATE INDEX city_travel_time_cityb_drivetime ON city_travel_time(cityb_id int4_ops,gmap_drive_time_minutes int4_ops);
