-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE processed_forecast (
    id SERIAL PRIMARY KEY,
    city_id integer NOT NULL REFERENCES city(id),
    date_forecasted date NOT NULL,
    max_consecutive_good_days integer NOT NULL,
    is_recommended boolean NOT NULL,
    good_days_csl text NOT NULL,
    ndays integer NOT NULL
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX processed_forecast_pkey ON processed_forecast(id int4_ops);
CREATE UNIQUE INDEX processed_forecast_city_id_date_forecasted_idx ON processed_forecast(city_id int4_ops,date_forecasted date_ops);
