-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE users (
    id integer DEFAULT nextval('user_id_seq'::regclass) PRIMARY KEY,
    email text,
    email_conf_uuid uuid DEFAULT uuid_generate_v4(),
    email_confirmed boolean NOT NULL DEFAULT false
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX user_email_idx ON users(email text_ops);
