-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE user_conf (
    conf_id uuid NOT NULL DEFAULT uuid_generate_v4(),
    conf_timestampz timestamp with time zone NOT NULL DEFAULT now(),
    user_id integer NOT NULL REFERENCES users(id)
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX user_conf_conf_id_idx ON user_conf(conf_id uuid_ops);
